### ISSUE TITLE
这套openvpn 有不通过docker搭建教程吗？很想学

### ISSUE THREAD

**Issue by 8080713** [GavinTan/openvpn#4]
作者大大，您这套openvpn 有不通过docker搭建教程吗？很想学

**Comment by GavinTan** [comment]
目前的openvpn-web还是依赖跟openvpn一起运行，所以如果你不通过docker话就要去参考build/Dockerfile里把安装的软件和添加的环境变量转换成在你要部署的本地执行，然后手动执行sh /usr/bin/docker-entrypoint.sh --init初始化生成配置文件。后面就运行起openvpn跟openvpn-web就好了

**Comment by GavinTan** [comment]
还有就是记得添加防火墙转发 doc/openvpn-install.txt里有说明

**Comment by 8080713** [comment]
好的，我去试试，谢谢作者大大
