### ISSUE TITLE
所有流量都走openvpn服务器后，无法使用IPv6上网。

### ISSUE THREAD

**Issue by Oppo-dev-tz** [GavinTan/openvpn#6]
大佬，我手机客户端是双栈ip，openvpn服务器是双栈ip。
服务器已设置所有流量走openvpn。
问题：手机客户端连接服务器的IPv6地址后，上网只能上纯IPv4网站，V6网站无法访问。用网站（http://ipv6-test.ch/index.html.zh_CN)检测，也只有服务器的v4 地址，无法使用服务器的v6地址访问外网。
请问应该怎么设置才能解决啊？

**Comment by GavinTan** [comment]
目前尚未添加ipv6支持，下个版本会添加

**Comment by GavinTan** [comment]
已经添加ipv6支持请使用最新镜像
