### ISSUE TITLE
是否可以将webui抽离出来，单独的一个 docker-compose 配置

### ISSUE THREAD

**Issue by xingcy08** [GavinTan/openvpn#7]
作者你好，因为我已经用 docker 装过了 openvpn，现在想在搞一个 webui 的界面。

网上搜寻看到了您的这个项目，但发现是和 openvpn 捆绑在一个 docker 镜像中的。

所以想用也用不了了，是否可以支持一下如题的需求？

**Comment by GavinTan** [comment]
这个考虑过独立出来但是web的一些功能比如生成客户端配置、更新证书之类的都需要去读取openvpn的配置证书，这就导致需要跟openvpn绑定在一起，这个没有好的解决办法
