### ISSUE TITLE
求助镜像部署疑问：OpenVPN服务好像没拉起来

### ISSUE THREAD

**Issue by SunPDZH** [GavinTan/openvpn#9]
修改默认VPN端口 1194 为 41194。
修改默认网页端口 8833 为 40080。

网页端能正常打开，客户端连接的时候，最后就未知错误了。
感觉像是OpenVPN服务端没拉起来。
telnet 尝试连接VPN也是连接不上：
Unable to connect to remote host: Connection refused.

netstat -ntpl如下：
![image](https://github.com/user-attachments/assets/9c0b512a-8add-4f81-a4d9-0eadf2904fec)

OpenVPN客户端连接日志如下：
![image](https://github.com/user-attachments/assets/de8cbc70-953d-4588-8e10-fea93d5f45c5)

**Comment by GavinTan** [comment]
可以在openvpn的服务器上telnet一下127.0.0.1 41194看看

**Comment by SunPDZH** [comment]
telnet 127.0.0.1 41194也连不上，如图：
![image](https://github.com/user-attachments/assets/3f53c7e5-0040-4684-855f-839ee18bc149)

**Comment by GavinTan** [comment]
那就要看看防火墙了是外面访问不进来
